services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: avito_parser
    ports:
      - "55433:5432"
    volumes:
      - avito_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d avito_parser"]
      interval: 5s
      timeout: 5s
      retries: 12

volumes:
  avito_pg_data:
